import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import {Metadata} from "next"

export const metadata:Metadata={
  title: {
    default: "Next.js -coderevolution",
    template: "%s | coderevolution",
    absolute :"",
  },
  description:"generated by himanshu"
}

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

   
export default function RootLayout({ children} : {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
     <header className="bg-blue-200">Header</header>
        {children}
  <footer className="bg-blue-200">footer</footer>
      </body>
    </html>
  );
}
