import { Geist, Geist_Mono } from "next/font/google";




const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function MarketingLayout({ children} : {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
     <header className="bg-blue-200">maketing header</header>
        {children}
  <footer className="bg-blue-200">marketing footer</footer>
      </body>
    </html>
  );
}
